// src/lib/components/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	let { class: cls = '', children }: { class?: string; children: Snippet } = $props();
</script>

<div
	class="rounded-xl border border-neutral-200 bg-white shadow-sm dark:border-neutral-800 dark:bg-neutral-800/50 {cls}"
>
	{@render children()}
</div>

// src/lib/components/Card.tsx
import type { ReactNode } from 'react';

export default function Card({
	className = '',
	children
}: {
	className?: string;
	children: ReactNode;
}) {
	return (
		<div
			className={`rounded-xl border border-neutral-200 bg-white shadow-sm dark:border-neutral-800 dark:bg-neutral-800/50 ${className}`}
		>
			{children}
		</div>
	);
}
